<?php
// $Id: cckpassword.module,v 1.3 2010/03/10 05:29:42 hefox Exp $

/**
 * @file
 * Defines simple cckpassword field types.
 */

/**
 * Implementation of hook_theme().
 */
function cckpassword_theme() {
  return array(
    'cckpassword_cckpasswordfield' => array(
      'arguments' => array('element' => NULL),
    ),
    'cckpassword_cckpassworddrupal' => array(
      'arguments' => array('element' => NULL),
    ),
    'cckpassword_formatter_default' => array(
      'arguments' => array('element' => NULL),
    ),
    'cckpassword_formatter_plain' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

function theme_cckpassword_cckpasswordfield($element) {
  return $element['#children'];
}


function theme_cckpassword_cckpassworddrupal($element) {
  return $element['#children'];
}

/**
 * Implementation of hook_elements().
 */
function cckpassword_elements() {
  return array(
    'cckpassword_cckpasswordfield' => array(
      '#input' => TRUE,
      '#columns' => array('value'),
      '#delta' => 0,
      '#process' => array('cckpassword_cckpasswordfield_process'),
    ),
    'cckpassword_cckpassworddrupal' => array(
      '#input' => TRUE,
      '#columns' => array('value'), 
      '#delta' => 0,
      '#process' => array('cckpassword_cckpassworddrupal_process'),
    ),
  );
}
function cckpassword_cckpasswordfield_process($element, $edit, $form_state, $form) {
  $field = $form['#field_info'][$element['#field_name']];
  $field_key = $element['#columns'][0];
  $delta = $element['#delta'];
  $element[$field_key] = array(
    '#type' => 'password',
    '#default_value' => isset($element['#value'][$field_key]) ? $element['#value'][$field_key] : NULL,
    '#size' => !empty($field['widget']['size']) ? $field['widget']['size'] : 60,
    '#attributes' => array('class' => 'text'),
    '#title' => $element['#title'],
    '#description' => $element['#description'],
    /*'#required' => $element['#required'],*/
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  $element[$field_key]['#maxlength'] = !empty($field['max_length']) ? $field['max_length'] : NULL;
  // Used so that hook_field('validate') knows where to flag an error.
  $element['_error_element'] = array(
    '#type' => 'value',
    '#value' => implode('][', array_merge($element['#parents'], array($field_key))),
  );
  if (!empty($element['#provide_delete'])) {
    $element['delete'] = array(
      '#type'=>'checkbox',
      '#title'=> t('Delete current password'),
      '#default_value'=> 0,
    );
  }
  return $element;
}

function cckpassword_cckpassworddrupal_process($element, $edit, $form_state, $form) {
  _user_password_dynamic_validation();
  $field = $form['#field_info'][$element['#field_name']];
  $field_key = $element['#columns'][0];
  $delta = $element['#delta'];
  $element[$field_key] = array(
    '#type' => 'password_confirm',
    '#default_value' => isset($element['#value'][$field_key]) ? $element['#value'][$field_key] : array(),
    '#size' => !empty($field['widget']['size']) ? $field['widget']['size'] : 60,
    '#attributes' => array('class' => 'text'),
    '#title' => $element['#title'],
    '#description' => $element['#description'],
    '#required' => $element['#required'],
    '#field_name' => $element['#field_name'],
    '#type_name' => $element['#type_name'],
    '#delta' => $element['#delta'],
    '#columns' => $element['#columns'],
  );
  $element[$field_key]['#maxlength'] = !empty($field['max_length']) ? $field['max_length'] : NULL;
  // Used so that hook_field('validate') knows where to flag an error.
  $element['_error_element'] = array(
    '#type' => 'value',
    '#value' => implode('][', array_merge($element['#parents'], array($field_key))),
  );
  if (!empty($element['#provide_delete'])) {
    $element['delete'] = array(
      '#type'=>'checkbox',
      '#title'=> t('Delete current password'),
      '#default_value'=> 0,
    );
  }
  return $element;
}


/**
 * Implementation of hook_field_info().
 */
function cckpassword_field_info() {
  return array(
    'cckpassword' => array(
      'label' => t('Password'),
      'description' => t('Store password in the database.'),
    ),
  );
}

/**
 * Implementation of hook_password_methods().
 */
function cckpassword_password_methods() {
  return array(
    'md5' => array(
      'title'=>'MD5 Hash',
      'functions'=> array(
        'presave'=>'cckpassword_md5',
      ),
      'max_length' => 32,
    ),
    'plain' => array(
      'title' => 'Plain text',
      'retrievable' => true,
      'functions'=> array(
      ),
      'max_length' => 255,
    ),
  );
}

function salt_password_methods() {
  return array(
    'salt' => array(
      'title'=>'Sitewide Salt',
      'functions'=> array(
        'presave'=>'cckpassword_just_add_salt',
      ),
      'max_length' => 32,
    ),
  );
}

/*presaves*/
function cckpassword_md5($items) {
  $items['value'] = md5($items['value']);
  return $items;
}

function cckpassword_just_add_salt($items) {
  $items['value'] = md5($items['value'] . variable_get('salt', ''));
  return $items;
}


/**
 * Return all, or one of the cck password storage methods.
 */
function _cckpassword_password_methods($method = NULL, $reset = NULL) {
  static $methods;
  if (empty($methods) || $reset) {
    $methods = module_invoke_all("password_methods");
    drupal_alter("password_methods",$methods);
  }
  if ($method) return $methods[$method];
  return $methods;
}
/**
 * Implementation of hook_field_settings().
 */
function cckpassword_field_settings($op, $field) {
  switch ($op) {
    case 'form':
      $methods = _cckpassword_password_methods();
      foreach($methods as $key => $info) {
        $options[$key] = $info['title'];
      }
      $form['method'] = array(
        '#title'=> t('Method'),
        '#description'=> t('Choice the method for storing and retrieving your passwords.<b>Warning:</b> Changing method will invalidate all previous values of this field.'),
        '#options' =>$options ,
        '#default_value'=>($field['method']?$field['method']:'md5'),
        '#type' => 'radios',
      );
      return $form;
    case 'save':
      return array('method');
    case 'database columns':
      $method = _cckpassword_password_methods($field['method']);
      $columns['value'] = array(
        'type' => 'varchar',
        'length' => $method['max_length']?$method['max_length']:32,
        'not null' => FALSE, 
        'sortable' => TRUE,
        'views' => TRUE
      );
      if (!empty($method['extra_fields'])) {
        $columns += $method['extra_fields'] ;
      }
      return $columns;
  }
}

/**
 * Implementation of hook_field().
 */
function cckpassword_field($op, &$node, $field, &$items, $teaser, $page) {
  switch ($op) {
    case 'sanitize':
      foreach ($items as $delta => $item) {
        $items[$delta]['safe'] = check_plain($item['value']);
      }
    break;
    case 'presave':
      if (empty($field['method'])) $field['method'] = 'md5';
      $method = _cckpassword_password_methods($field['method']);
      $field_name = $field['field_name'];
      $old_vals = content_storage('load',$node);
      $old_vals = $old_vals[$field_name] ;
      if (is_array($items)) {
        
        foreach ($items as $delta => $item) {
          $error_element = isset($item['_error_element']) ? $item['_error_element'] : '';
          if (is_array($item) && isset($item['_error_element'])) unset($item['_error_element']);
          if (!empty($item['value'])) {
            $presave = $method['functions']['presave'];
            
            if ($presave && function_exists($presave)) {
              $items[$delta] = call_user_func($presave,$items[$delta]);
            }
          } elseif ($item['delete']) {
            $items[$delta]['value'] =  '';
          } elseif ($old_vals[$delta]) {
            $items[$delta] = $old_vals[$delta];
          }
        }
      } else {
        $items = $old_vals; 
      }
      
      $node->$field_name = $items;
      return $items;
  }
}

/**
 * Implementation of hook_content_is_empty().
 */
function cckpassword_content_is_empty($item, $field) {
  if (empty($item['value'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_field_formatter_info().
 */
function cckpassword_field_formatter_info() {
  return array(
    'default' => array(
      'label' => t('None'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
    'plain' => array(
      'label' => t('Plain'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
    ),
  );
}

/**
 * Theme function for 'default' cckpassword field formatter.
 */
function theme_cckpassword_formatter_default($element) {
  return '';
}

/**
 * Theme function for 'plain' cckpassword field formatter.
 */
function theme_cckpassword_formatter_plain($element) {
  return ($allowed =_text_allowed_values($element)) ? $allowed : $element['#item']['safe'];
}

/**
 * Implementation of hook_widget_info().
 *
 */
function cckpassword_widget_info() {
  return array(
    'cckpassword_cckpasswordfield' => array(
      'label' => t('Plain Password field'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
    'cckpassword_cckpassworddrupal' => array(
      'label' => t('Drupal password field'),
      'field types' => array('cckpassword'),
      'multiple values' => CONTENT_HANDLE_CORE,
      'callbacks' => array(
        'default value' => CONTENT_CALLBACK_DEFAULT,
      ),
    ),
  );
}



/**
 * Implementation of hook_widget().
 *
 */
function cckpassword_widget(&$form, &$form_state, $field, $items, $delta = 0) {
  $element = array(
    '#type' => $field['widget']['type'],
    '#default_value' => '',
    '#provide_delete' => !empty($items[$delta]['value']),
  );  
  return $element;
}